### ISSUE TITLE
Sidebar Panel Buttons way too spaced after update

### ISSUE THREAD

**Issue by Sharkcruiser** [darklinkpower/Harmony#32]
### Feature Description

Hey its not rly a feature request or a bug, but since a new update the buttons on the sidebar panel are way too spaced and dont even all fit on the window anymore and you have to scroll to see them all
They look nicer now and more mordern, but would it be possible to be able to customize how far they are apart?

Thanks in advance

### Screenshots

![grafik](https://github.com/user-attachments/assets/65cef411-4e1f-494d-abbf-9c9141306905)

**Comment by darklinkpower** [comment]
I understand your point of view but it's a difficult situation because some people may like a change and others wouldn't. In my experience it's not possible for everyone to globally like something so in those situations, in my opinion it's better to modify your local installation to your liking, I hope it's understandable.

In this case you can change the number `15` in the line here to to whatever value works for you: https://github.com/darklinkpower/Harmony/blob/6b8496308cf4028059bb023cfc2623cc98e6acea/source/CustomControls/SidebarItem.xaml#L13

I hope this helps, and feel free to reach out if you have any other questions.

**Comment by Sharkcruiser** [comment]
Hey no worries I understand
Thats why I put it more in feature request to maybe make it adjustable with theme modifier or smth else 

Thanks for the reply and I will just edit the code then :)

great theme btw, thanks for all your work on it

**Comment by darklinkpower** [comment]
Closing under
